### ISSUE TITLE
Invalid token. Try again

### ISSUE THREAD

**Issue by DRIVER1ksa** [s-a-ng/elevenlabs-voicechanger#2]
its keep saying that "Invalid token. Try again"

i add it like that "Bearer 12345678"

**Comment by s-a-ng** [comment]
I have updated the code to use a ElevenLabs API key instead of a Bearer token.

Speech to speech was not fully released at the time of this being written.

**Comment by DRIVER1ksa** [comment]
thank you very much,i want to support this project by making donation. plz give me your donation link.
